import type { Pricing } from "./schema";

export const SEED_DATE = "2026-09-28";

export const SEED: Record<string, Pricing> = {
  boat: {
    tech: "Full Ubuntu 24.04 VM (own kernel, systemd, Docker); shared vCPUs",
    billing_summary:
      "Per-second billing for running time, drawn from a monthly plan whose full price comes back as machine time.",
    metered: null,
    sizes: [
      { name: "small", vcpu: 2, ram_gb: 4, disk_gb: 12, usd_per_hour: 0.018, usd_per_month_flat: null, gpu: null, plan: null, note: "12 GB of user space; the OS sits outside it" },
      { name: "default", vcpu: 4, ram_gb: 8, disk_gb: 50, usd_per_hour: 0.036, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "large", vcpu: 8, ram_gb: 16, disk_gb: 125, usd_per_hour: 0.072, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "xlarge", vcpu: 16, ram_gb: 32, disk_gb: 251, usd_per_hour: 0.2, usd_per_month_flat: null, gpu: null, plan: null, note: "Needs the $100 plan or higher; allocated by an operator" },
    ],
    stopped_disk_gb_month: 0,
    plans: [
      { name: "$20", usd_per_month: 20, usage_credit_usd: 20, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 8, max_ram_gb: 16, max_disk_gb: null, summary: "100 concurrent sandboxes. The $20 comes back as machine time; top up with $20 packs that never expire." },
      { name: "$100", usd_per_month: 100, usage_credit_usd: 100, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 16, max_ram_gb: 32, max_disk_gb: null, summary: "300 concurrent sandboxes" },
      { name: "$500", usd_per_month: 500, usage_credit_usd: 500, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 16, max_ram_gb: 32, max_disk_gb: null, summary: "1,000 concurrent sandboxes" },
      { name: "$2000", usd_per_month: 2000, usage_credit_usd: 2000, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 16, max_ram_gb: 32, max_disk_gb: null, summary: "2,000 concurrent sandboxes" },
    ],
    egress_usd_per_gb: 0,
    egress_note: "Up to 2 TB per sandbox per month included",
    free_credit: "25 free hours on the trial (card required)",
    scales_to_zero: false,
    idle_summary:
      "Stopped sandboxes are free and keep their disk. Auto-stop runs on a TTL from start (1 h by default, up to 30 days), not on idleness.",
    max_size: "16 vCPU / 32 GB / 251 GB (xlarge, on request); 8 vCPU / 16 GB self-serve",
    features: ["Snapshot, fork and templates", "SSH, root, Docker, systemd", "Public IPv4/IPv6 and HTTPS", "60fps browser desktop", "Nested KVM on bare-metal hosts", "EU regions only"],
    caveats: ["vCPUs are shared, although the homepage says 'dedicated'", "Storage price for extra named snapshots is not published"],
    upcoming_changes: [],
  },

  "exe-dev": {
    tech: "Full VMs on Cloud Hypervisor, booted from container images",
    billing_summary:
      "Flat monthly price for a pool of CPU and RAM shared by up to 50 VMs, plus disk and bandwidth overage.",
    metered: null,
    sizes: [
      { name: "Small pool", vcpu: 2, ram_gb: 8, disk_gb: 100, usd_per_hour: null, usd_per_month_flat: 20, gpu: null, plan: null, note: "Shared by up to 50 VMs" },
      { name: "Medium pool", vcpu: 4, ram_gb: 16, disk_gb: 200, usd_per_hour: null, usd_per_month_flat: 40, gpu: null, plan: null, note: null },
      { name: "Large pool", vcpu: 8, ram_gb: 32, disk_gb: 400, usd_per_hour: null, usd_per_month_flat: 80, gpu: null, plan: null, note: null },
      { name: "XLarge pool", vcpu: 16, ram_gb: 64, disk_gb: 800, usd_per_hour: null, usd_per_month_flat: 160, gpu: null, plan: null, note: null },
    ],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Team", usd_per_month: null, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 16, max_ram_gb: 64, max_disk_gb: null, summary: "$25 / $50 / $100 / $200 per user for the same pools, with SSO and bursting into teammates' capacity" },
      { name: "Enterprise", usd_per_month: null, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 640, max_ram_gb: 2560, max_disk_gb: null, summary: "$0.07 per vCPU-hour including 4 GB RAM per vCPU; pools start at 32 vCPU" },
    ],
    egress_usd_per_gb: 0.05,
    egress_note: "200 GB per month included",
    free_credit: "30-day trial through invite links",
    scales_to_zero: false,
    idle_summary: "VMs are always on and the price is flat whether they're busy or idle.",
    max_size: "16 vCPU / 64 GB self-serve; Enterprise pools up to 640 vCPU",
    features: ["Up to 50 VMs share one pool", "SSH-first, HTTPS proxy and custom domains", "Built-in Shelley coding agent with $20/mo of LLM credit", "9 regions"],
    caveats: ["No per-VM public IP", "Extra disk beyond the pool is $0.08/GB-month", "No snapshots or scale-to-zero"],
    upcoming_changes: [],
  },

  machine0: {
    tech: "Full KVM VMs on DigitalOcean; shared vCPUs except -premium sizes",
    billing_summary: "Prepaid wallet billed per minute at a fixed hourly rate per size. Same price in every region.",
    metered: null,
    sizes: [
      { name: "small", vcpu: 1, ram_gb: 1, disk_gb: 25, usd_per_hour: 0.013, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "medium", vcpu: 2, ram_gb: 2, disk_gb: 60, usd_per_hour: 0.034, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "large", vcpu: 2, ram_gb: 4, disk_gb: 80, usd_per_hour: 0.052, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "large-nvme", vcpu: 2, ram_gb: 4, disk_gb: 80, usd_per_hour: 0.061, usd_per_month_flat: null, gpu: null, plan: null, note: "Newer CPU and NVMe" },
      { name: "xl", vcpu: 4, ram_gb: 8, disk_gb: 160, usd_per_hour: 0.104, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "xxl", vcpu: 8, ram_gb: 16, disk_gb: 320, usd_per_hour: 0.208, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "xl-premium", vcpu: 4, ram_gb: 8, disk_gb: 50, usd_per_hour: 0.236, usd_per_month_flat: null, gpu: null, plan: null, note: "Dedicated vCPUs" },
      { name: "xxl-premium", vcpu: 8, ram_gb: 16, disk_gb: 100, usd_per_hour: 0.473, usd_per_month_flat: null, gpu: null, plan: null, note: "Dedicated vCPUs" },
      { name: "xxxl", vcpu: 16, ram_gb: 64, disk_gb: 200, usd_per_hour: 0.825, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "4xl", vcpu: 32, ram_gb: 128, disk_gb: 480, usd_per_hour: 1.98, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "5xl", vcpu: 48, ram_gb: 192, disk_gb: 720, usd_per_hour: 2.97, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "6xl", vcpu: 60, ram_gb: 240, disk_gb: 900, usd_per_hour: 3.714, usd_per_month_flat: null, gpu: null, plan: null, note: null },
      { name: "gpu-4000ada-1", vcpu: 8, ram_gb: 32, disk_gb: 500, usd_per_hour: 0.836, usd_per_month_flat: null, gpu: "1× RTX 4000 Ada 20 GB", plan: null, note: null },
      { name: "gpu-l40s-1", vcpu: 8, ram_gb: 64, disk_gb: 500, usd_per_hour: 1.727, usd_per_month_flat: null, gpu: "1× L40S 48 GB", plan: null, note: null },
      { name: "gpu-h100-1", vcpu: 20, ram_gb: 240, disk_gb: 720, usd_per_hour: 4.851, usd_per_month_flat: null, gpu: "1× H100 80 GB", plan: null, note: null },
      { name: "gpu-h200-1", vcpu: 24, ram_gb: 240, disk_gb: 720, usd_per_hour: 4.917, usd_per_month_flat: null, gpu: "1× H200 141 GB", plan: null, note: null },
      { name: "gpu-h200-8", vcpu: 192, ram_gb: 1920, disk_gb: 2000, usd_per_hour: 39.336, usd_per_month_flat: null, gpu: "8× H200", plan: null, note: null },
    ],
    stopped_disk_gb_month: 0.078,
    plans: [],
    egress_usd_per_gb: 0.01,
    egress_note: "1–10 TB free depending on size",
    free_credit: null,
    scales_to_zero: false,
    idle_summary:
      "A stopped VM still bills at the full rate. Suspending snapshots it and bills only image storage ($0.078/GB-month) until you resume.",
    max_size: "60 vCPU / 240 GB (6xl); GPUs up to 8× H200",
    features: ["Per-minute billing", "GPUs from RTX 4000 Ada to 8× H200", "Suspend/resume snapshots", "Static IP and HTTPS URL", "CLI with --json and a remote MCP server", "5 regions"],
    caveats: ["8× H100 is listed at $34.232/h on the homepage and $38.808/h in the docs"],
    upcoming_changes: [],
  },

  sail: {
    tech: "Kernel-isolated Linux VMs, live-migrated between hosts",
    billing_summary:
      "Billed on observed CPU, RAM and NVMe use, sampled every 15 s. Nothing is billed while asleep.",
    metered: {
      base_per_hour: 0,
      vcpu_hour: 0.015,
      ram_gb_hour: 0.008,
      cpu_basis: "used",
      ram_basis: "used",
      disk_gb_month_always: 0,
      disk_gb_month_awake: 0.511,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Free", usd_per_month: 0, usage_credit_usd: 5, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 8, max_ram_gb: 256, max_disk_gb: null, summary: "$5/month of credit once a card is attached; small per-Sailbox creation fee" },
      { name: "Pro", usd_per_month: 250, usage_credit_usd: 100, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 8, max_ram_gb: 256, max_disk_gb: null, summary: "5,000 concurrent Sailboxes, no creation fees, $100/month of credit" },
    ],
    egress_usd_per_gb: null,
    egress_note: "Not published",
    free_credit: "$5 per month with a card on file",
    scales_to_zero: true,
    idle_summary:
      "Auto-sleeps after 30 s idle by default (checkpointing memory and disk), even while waiting on an LLM reply. Asleep costs $0 apart from optional volumes.",
    max_size: "8 vCPU, up to 256 GiB RAM and 1 TiB disk (size l)",
    features: ["No runtime limit", "Memory + disk checkpoints and fork", "Local NVMe, Docker-in-Docker", "SSH devboxes with coding agents preinstalled", "Egress allowlists and credential injection"],
    caveats: ["Persistent volumes bill separately at about $0.30/GiB-month", "Live migration adds a few seconds of latency a few times a day"],
    upcoming_changes: [],
  },

  ix: {
    tech: "Full VMs on bare-metal AMD EPYC Zen 5, NixOS guests",
    billing_summary: "Per-second metering on vCPU time actually burned, RAM actually touched and disk actually used.",
    metered: {
      base_per_hour: 0,
      vcpu_hour: 0.0288,
      ram_gb_hour: 0.0108,
      cpu_basis: "used",
      ram_basis: "used",
      disk_gb_month_always: 0.101,
      disk_gb_month_awake: 0,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [],
    egress_usd_per_gb: null,
    egress_note: "Not published yet",
    free_credit: null,
    scales_to_zero: false,
    idle_summary:
      "Idle cores cost nothing, but a running VM still pays for RAM it has touched. A stopped VM bills disk only; there's no automatic sleep.",
    max_size: "Up to 256 GiB RAM; 64 or 100 vCPU depending on the page",
    features: ["Live snapshots and restore into many machines", "Live migration", "Declarative NixOS config", "Deduplicated disk", "Managed GitHub Actions runners"],
    caveats: ["vCPU ceiling is 64 on the pricing page and 100 in the docs", "Automatic guest swap is announced but not live"],
    upcoming_changes: [],
  },

  freestyle: {
    tech: "Hardware-virtualized VMs on bare metal with nested virtualization",
    billing_summary:
      "Per-second billing on the size allocated. Paid plans are a monthly minimum that counts as usage credit.",
    metered: {
      base_per_hour: 0,
      vcpu_hour: 0.04032,
      ram_gb_hour: 0.0129,
      cpu_basis: "allocated",
      ram_basis: "allocated",
      disk_gb_month_always: 0.0628,
      disk_gb_month_awake: 0,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Free", usd_per_month: 0, usage_credit_usd: 0, included_vcpu_hours: 200, included_ram_gb_hours: 400, included_disk_gb_months: 82, hard_cap: true, max_vcpu: 4, max_ram_gb: 8, max_disk_gb: 32, summary: "Allowances are hard caps: VMs pause until the monthly reset" },
      { name: "Hobby", usd_per_month: 50, usage_credit_usd: 50, included_vcpu_hours: 200, included_ram_gb_hours: 400, included_disk_gb_months: 82, hard_cap: false, max_vcpu: 8, max_ram_gb: 16, max_disk_gb: 64, summary: "You pay the greater of $50 or your usage above the allowances" },
      { name: "Pro", usd_per_month: 500, usage_credit_usd: 500, included_vcpu_hours: 200, included_ram_gb_hours: 400, included_disk_gb_months: 82, hard_cap: false, max_vcpu: 32, max_ram_gb: 64, max_disk_gb: 256, summary: "400 concurrent VMs" },
    ],
    egress_usd_per_gb: 0.02,
    egress_note: "50 GB included on Free, 500 GB on paid plans",
    free_credit: "Monthly allowances of 200 vCPU-h and 400 GiB-h RAM on every plan",
    scales_to_zero: false,
    idle_summary: "Paused VMs keep memory and processes and bill storage only. An optional idle timeout auto-pauses on no network activity.",
    max_size: "32 vCPU / 64 GiB self-serve; 64 vCPU / 128 GiB on request",
    features: ["Live fork including memory", "Pause/resume", "SSH and nested virtualization", "VPCs and WireGuard", "Managed HTTPS and custom domains"],
    caveats: ["The pricing page and the docs disagree on whether the Free plan gets persistent VMs"],
    upcoming_changes: [],
  },

  sprites: {
    tech: "Firecracker microVMs with tiered NVMe + object storage",
    billing_summary: "Metered on CPU time used, memory used and storage. Idle Sprites sleep and stop billing compute.",
    metered: {
      base_per_hour: 0,
      vcpu_hour: 0.07,
      ram_gb_hour: 0.04375,
      cpu_basis: "used",
      ram_basis: "used",
      disk_gb_month_always: 0.02,
      disk_gb_month_awake: 0.5,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Pay as you go", usd_per_month: 0, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 8, max_ram_gb: 16, max_disk_gb: null, summary: "Low limit on concurrently active Sprites" },
      { name: "Adventurer", usd_per_month: 20, usage_credit_usd: 0, included_vcpu_hours: 450, included_ram_gb_hours: 1800, included_disk_gb_months: 50, hard_cap: false, max_vcpu: 8, max_ram_gb: 16, max_disk_gb: null, summary: "20 active + 20 warm Sprites" },
      { name: "Veteran", usd_per_month: 50, usage_credit_usd: 0, included_vcpu_hours: 800, included_ram_gb_hours: 3200, included_disk_gb_months: 100, hard_cap: false, max_vcpu: 8, max_ram_gb: 16, max_disk_gb: null, summary: "50 active + 50 warm" },
      { name: "Hero", usd_per_month: 100, usage_credit_usd: 0, included_vcpu_hours: 1200, included_ram_gb_hours: 4800, included_disk_gb_months: 150, hard_cap: false, max_vcpu: 8, max_ram_gb: 16, max_disk_gb: null, summary: "100 active + 100 warm, standard support" },
      { name: "Champion", usd_per_month: 200, usage_credit_usd: 0, included_vcpu_hours: 1800, included_ram_gb_hours: 7200, included_disk_gb_months: 225, hard_cap: false, max_vcpu: 8, max_ram_gb: 16, max_disk_gb: null, summary: "200 active + 200 warm" },
      { name: "Legend", usd_per_month: 500, usage_credit_usd: 0, included_vcpu_hours: 3200, included_ram_gb_hours: 12500, included_disk_gb_months: 400, hard_cap: false, max_vcpu: 8, max_ram_gb: 16, max_disk_gb: null, summary: "500 active + 500 warm" },
    ],
    egress_usd_per_gb: 0,
    egress_note: "Not metered today",
    free_credit: "$30 one-time trial credit",
    scales_to_zero: true,
    idle_summary: "Goes warm then cold seconds after activity stops; asleep bills only cold storage. Wakes on HTTP in 100 ms–2 s.",
    max_size: "8 vCPU / 8 GB (16 GB on request) / 100 GB",
    features: ["Checkpoint/restore of the whole filesystem in ~1 s", "Per-Sprite HTTPS URL with wake-on-request", "Credential connectors and egress policies", "SDKs for JS, Go, Python, Elixir"],
    caveats: ["The plan table comes from the Sprites FAQ and forum; fly.io/pricing says Sprites have no tiers", "Hot storage (~$0.50/GB-month) bills only while awake"],
    upcoming_changes: [
      { effective_date: "2026-10-01", summary: "CPU drops from $0.07 to $0.03825 per vCPU-hour and memory from $0.04375 to $0.021875 per GB-hour" },
    ],
  },

  boxd: {
    tech: "Custom Rust VMM on KVM (not Firecracker)",
    billing_summary:
      "Prepaid credits metered per second: vCPU on machine size while running, RAM on what's resident, disk on what's written.",
    metered: {
      base_per_hour: 0,
      vcpu_hour: 0.059,
      ram_gb_hour: 0.018,
      cpu_basis: "allocated",
      ram_basis: "used",
      disk_gb_month_always: 0.0876,
      disk_gb_month_awake: 0,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Pay as you go", usd_per_month: 0, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 4, max_ram_gb: 16, max_disk_gb: 100, summary: "50 machines per org; bigger machines on request" },
    ],
    egress_usd_per_gb: null,
    egress_note: "Not published",
    free_credit: "$30 / €30 of credit when a card is added",
    scales_to_zero: true,
    idle_summary: "Auto-hibernates after 4 h with no inbound traffic and then bills disk only; wakes in ~85 ms.",
    max_size: "4 vCPU / 16 GiB / 100 GB self-serve",
    features: ["Live fork of a running machine in 100–200 ms", "Snapshots and checkpoints", "HTTPS URL per machine, raw TCP/UDP", "Self-hostable single binary", "EU hosting"],
    caveats: ["Priced in EUR first; USD rates are boxd's own", "Prices exclude VAT"],
    upcoming_changes: [],
  },

  smol: {
    tech: "libkrun microVMs with their own guest kernel",
    billing_summary:
      "A base fee per running machine-hour plus active vCPU, resident memory and used disk, billed to the second.",
    metered: {
      base_per_hour: 0.04,
      vcpu_hour: 0.05,
      ram_gb_hour: 0.0162,
      cpu_basis: "used",
      ram_basis: "used",
      disk_gb_month_always: 0.073,
      disk_gb_month_awake: 0,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Standard", usd_per_month: 0, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 8, max_ram_gb: 16, max_disk_gb: null, summary: "20 machines; idle apps scale to zero" },
      { name: "Pro", usd_per_month: 20, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 16, max_ram_gb: 24, max_disk_gb: 200, summary: "100 machines; apps can stay always-on" },
      { name: "Startup", usd_per_month: 150, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 32, max_ram_gb: 32, max_disk_gb: 200, summary: "1,000 machines, priority support" },
    ],
    egress_usd_per_gb: 0.05,
    egress_note: null,
    free_credit: "$100 one-time sign-up credit, no card needed",
    scales_to_zero: true,
    idle_summary:
      "An idle running machine pays the $0.04/h base plus near-zero usage. Stopped machines pay only for disk.",
    max_size: "32 vCPU / 32 GB / 200 GB (Startup)",
    features: ["Open-source engine runs the same VMs locally", "Boots any OCI image", "Branching/forking", "Free exec calls", "Warm pools on every plan"],
    caveats: ["Always-on apps need Pro ($20/mo); the estimate doesn't add it", "Cloud snapshot API not implemented yet"],
    upcoming_changes: [],
  },

  e2b: {
    tech: "Firecracker microVM",
    billing_summary: "Billed per second for allocated vCPU and RAM while a sandbox runs; disk is included in the plan.",
    metered: {
      base_per_hour: 0,
      vcpu_hour: 0.0504,
      ram_gb_hour: 0.0162,
      cpu_basis: "allocated",
      ram_basis: "allocated",
      disk_gb_month_always: 0,
      disk_gb_month_awake: 0,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Hobby", usd_per_month: 0, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 8, max_ram_gb: 8, max_disk_gb: 10, summary: "20 concurrent sandboxes, 1-hour continuous runtime, 10 GiB disk" },
      { name: "Pro", usd_per_month: 150, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 8, max_ram_gb: 8, max_disk_gb: 20, summary: "$150/month plus usage; 100 concurrent sandboxes, 24-hour continuous runtime, 20 GiB disk" },
      { name: "Enterprise", usd_per_month: null, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: null, max_ram_gb: null, max_disk_gb: null, summary: "Custom limits and BYOC, $3,000 monthly minimum" },
    ],
    egress_usd_per_gb: null,
    egress_note: "Not published",
    free_credit: "$100 one-time, no card required",
    scales_to_zero: true,
    idle_summary: "Sandboxes stop when their timeout expires and can auto-pause; paused sandboxes aren't billed.",
    max_size: "8 vCPU / 8 GiB / 20 GiB on Pro",
    features: ["Pause and resume with memory state", "Snapshots and fork", "Egress rules and secret injection", "BYOC on Enterprise"],
    caveats: ["Continuous runtime is capped at 1 h (Hobby) or 24 h (Pro); pause and resume to run longer", "Pro+ and Pro++ concurrency add-ons ($650 and $1,150 total) aren't modeled"],
    upcoming_changes: [],
  },

  daytona: {
    tech: "Linux containers by default; optional Linux or Windows VM sandboxes",
    billing_summary: "Billed per second for reserved vCPU, RAM and disk; stopped sandboxes pay only for disk.",
    metered: {
      base_per_hour: 0,
      vcpu_hour: 0.0504,
      ram_gb_hour: 0.0162,
      cpu_basis: "allocated",
      ram_basis: "allocated",
      disk_gb_month_always: 0.0788,
      disk_gb_month_awake: 0,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Pay as you go", usd_per_month: 0, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 4, max_ram_gb: 8, max_disk_gb: null, summary: "Prepaid wallet; org limits grow with top-up tier" },
      { name: "Enterprise", usd_per_month: null, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: null, max_ram_gb: null, max_disk_gb: null, summary: "Custom limits, SSO, audit logs and BYOC" },
    ],
    egress_usd_per_gb: null,
    egress_note: "Not published; lower tiers get restricted outbound access",
    free_credit: "$200 of free compute",
    scales_to_zero: true,
    idle_summary: "Sandboxes auto-stop after 15 min idle and archive after 7 days; stopped ones pay for disk only, archived ones nothing.",
    max_size: "4 vCPU / 8 GiB / 10 GiB per sandbox by default",
    features: ["Per-second billing", "VM sandboxes with pause, fork and nested virtualization", "Windows sandboxes", "GPU sandboxes", "US and EU regions"],
    caveats: ["Default per-sandbox disk is 10 GiB; larger needs a raised limit", "First 5 GiB of disk is free, which the estimate ignores", "Windows vCPU is $0.0858/h"],
    upcoming_changes: [],
  },

  modal: {
    tech: "gVisor-isolated containers (full-VM runtime in beta)",
    billing_summary: "Billed per second for CPU and memory, on whichever is higher: what you requested or what you used.",
    metered: {
      base_per_hour: 0,
      vcpu_hour: 0.070956,
      ram_gb_hour: 0.024012,
      cpu_basis: "allocated",
      ram_basis: "allocated",
      disk_gb_month_always: 0,
      disk_gb_month_awake: 0,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Starter", usd_per_month: 0, usage_credit_usd: 30, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: null, max_ram_gb: null, max_disk_gb: null, summary: "$30/month of free compute, 100 containers at once" },
      { name: "Team", usd_per_month: 250, usage_credit_usd: 100, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: null, max_ram_gb: null, max_disk_gb: null, summary: "$250/month plus usage, $100/month of compute included, 5,000 containers" },
      { name: "Enterprise", usd_per_month: null, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: null, max_ram_gb: null, max_disk_gb: null, summary: "Volume discounts, SSO, audit logs, HIPAA" },
    ],
    egress_usd_per_gb: 0,
    egress_note: "Free until Oct 1, 2026",
    free_credit: "$30 of compute every month on Starter",
    scales_to_zero: false,
    idle_summary: "An idle sandbox bills for its request until its timeout (5 min default, 24 h max) or an optional idle timeout ends it.",
    max_size: "Not published; enforced when a sandbox is created",
    features: ["Filesystem, directory and memory snapshots", "GPU sandboxes", "Region selection", "Tunnels for exposing ports"],
    caveats: ["Priced per physical core; 1 core = 2 vCPU", "Sandboxes live at most 24 h; long jobs restart from a snapshot", "Pinning a region multiplies the price by 1.15× or 1.75×"],
    upcoming_changes: [
      { effective_date: "2026-10-01", summary: "Egress billed at $0.04/GiB above the plan allowance (1 TiB Starter, 10 TiB Team)" },
    ],
  },

  morph: {
    tech: "Full VMs with Infinibranch snapshot and branching",
    billing_summary: "Running VMs are billed in compute units ($0.05 each per hour), counting the largest of vCPUs, RAM ÷ 4 GiB and disk ÷ 16 GiB.",
    metered: {
      base_per_hour: 0,
      vcpu_hour: 0.05,
      ram_gb_hour: 0,
      cpu_basis: "allocated",
      ram_basis: "allocated",
      disk_gb_month_always: 0.0073,
      disk_gb_month_awake: 0,
    },
    sizes: [],
    stopped_disk_gb_month: null,
    plans: [
      { name: "Developer", usd_per_month: 0, usage_credit_usd: 0, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 64, max_ram_gb: 256, max_disk_gb: 1000, summary: "Pay as you go at $0.05 per compute unit" },
      { name: "Team", usd_per_month: 40, usage_credit_usd: 50, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 256, max_ram_gb: 1024, max_disk_gb: null, summary: "$40/month buys 1,000 compute units ($50 worth)" },
      { name: "Scale", usd_per_month: 250, usage_credit_usd: 375, included_vcpu_hours: 0, included_ram_gb_hours: 0, included_disk_gb_months: 0, hard_cap: false, max_vcpu: 1024, max_ram_gb: 4096, max_disk_gb: 16000, summary: "$250/month buys 7,500 compute units ($375 worth)" },
    ],
    egress_usd_per_gb: null,
    egress_note: "Not published",
    free_credit: null,
    scales_to_zero: false,
    idle_summary: "A TTL can pause a VM and wake-on-HTTP/SSH resumes it; paused VMs bill only snapshot storage.",
    max_size: "64 vCPU / 256 GB on Developer, up to 1,024 vCPU on Scale",
    features: ["Instant snapshot, branch and pause/resume with memory", "Wake on HTTP or SSH", "TTL auto-pause", "Devboxes and GitHub Actions runners"],
    caveats: ["Modeled as $0.05 per vCPU-hour with RAM free; exact only up to 4 GiB RAM and 16 GiB disk per vCPU", "Price of extra compute units on paid plans assumed to be $0.05"],
    upcoming_changes: [],
  },
};
